version: '2'
services:
    ols-web:
      build:
          context: .
          dockerfile: ols-web/Dockerfile
      environment:
        - spring.data.solr.host=http://${MONGODB_IP}:8983/solr
        - spring.data.mongodb.host=${MONGODB_IP}
        - OLS_HOME=/mnt/
      volumes:
        - ols-neo4j-data:/mnt/neo4j 
      ports:
      - 8080:8080
volumes:
    ols-neo4j-data:
        external: true

